### ISSUE TITLE
Queries Regarding TaxaNorm Tool Application to Metaproteomics Data

### ISSUE THREAD

**Issue by MonicaSteffi** [wangziyue57/TaxaNorm#6]
Dear author,

I appreciate your provision of the TaxaNorm tool. I have a couple of inquiries:

1. I am working with metaproteomics data, aiming to observe the impact of microbial proteins under specific conditions. Would it be appropriate to apply TaxaNorm to this type of data without any adjustments?

2. Additionally, some features were not detected in all samples. How does TaxaNorm handle missing values? Would it be meaningful to consider the imputed values in such cases?

**Comment by wangziyue57** [comment]
TaxaNorm should work for metaproteomics data, as long as the input data is in the count matrix format. But be aware that we haven't test for metaproteomics at our site.

Unfortunately, TaxaNorm doesn't handle missing values. It's advised that imputation should be done before applying TaxaNorm.
