### ISSUE TITLE
Please undo any changes you do to future::plan()

### ISSUE THREAD

**Issue by HenrikBengtsson** [wangziyue57/TaxaNorm#7]
Congrats to the CRAN release.

Author of Futurverse here.  I've got some comments on the parallelization code in:

https://github.com/wangziyue57/TaxaNorm/blob/2dcf392e11ee99a072dbd9b83be5e3dbb85f34ca/R/norm_func_ZINB.R#L79-L84

Please undo any changes you do to `future::plan()`.  If not, you might break other code that the user runs.  This is explained in Section 'For package developers' of [`?future::plan`](https://future.futureverse.org/reference/plan.html).  That section also shows how to undo settings.  This one is important.

Also, for reasons that I bring up in <https://www.jottr.org/2022/12/05/avoid-detectcores/>,

1. please don't use `parallel::detectCores()`, and
2. please don't default to using all cores, or almost all cores.  It's also a big no-no on CRAN.

Even if I cannot convince you to agree with me on the above, maybe you could replace:

```r
if (is.null(ncores)) {ncores <- max(1, parallel::detectCores() - 1)} 
```

with

```r
if (is.null(ncores)) {ncores <- parallelly::availableCores(omit = 1)}
```

It'll give sysadms a chance to control the number of default CPU cores.

**Comment by HenrikBengtsson** [comment]
Forgot to mention that in:

```r
if (.Platform$OS.type == "windows" | parallelly::supportsMulticore() == FALSE) {
```

you want to use `||` rather than `|`.   You can also use `! parallelly::supportsMulticore()`, which is more common.

**Comment by wangziyue57** [comment]
Thanks a lot for the suggestion! We're working on updating the package and will incorporate this in the newer version.
